type: object
required:
- name
- version
- platforms
- imgname
- tags
- dir
properties:
  name:
    type: string
    description: The display name of the image
  version:
    type: string
    description: The version of the image
  platforms:
    type: array
    description: The platforms the image supports
    items:
      type: string
  imgname:
    type: string
    description: The name of the image
  tags:
    type: array
    description: The tags of the image
    items:
      type: string
  dir:
    type: string
    description: The directory of the Dockerfile
  files:
    type: object
    properties:
      dockerfile:
        type: string
        description: The file name of the Dockerfile
      dockleignore:
        type: string
        description: The file path of the dockleignore file
