type: object
required:
- name
- imgname
- variant
- platforms
properties:
  name:
    type: string
    description: The display name of the image
  imgname:
    type: string
    description: The name of the image
  variant:
    type: string
    description: The variant of the image
  platforms:
    type: array
    description: The platforms the image supports
    items:
      type: string
  tags:
    type: array
    description: The tags of the image
    items:
      type: string
  dir:
    type: string
    description: The directory of the Dockerfile
  files:
    type: object
    properties:
      dockerfile:
        type: string
        description: The file name of the Dockerfile
      dockleignore:
        type: string
        description: The file path of the dockleignore file
  buildArgs:
    type: object
    description: key-value maps of Docker build arguments
  noCache:
    type: boolean
    description: Disable cache when building Docker image
