apiVersion: v1
kind: Pod
metadata:
  name: nvidia-gpu-device-plugin
  namespace: kube-system
  labels:
    app: nvidia-gpu-device-plugin
spec:
  hostNetwork: true
  hostPID: true
  priorityClassName: system-node-critical
  tolerations:
    - operator: Exists
  containers:
    - name: nvidia-gpu-device-plugin
      image: nvcr.io/nvidia/k8s-device-plugin:stable
      args: ["--fail-on-init-error=false"]
      securityContext:
        privileged: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      volumeMounts:
        - name: kubelet-device-plugin-socket
          mountPath: /var/lib/kubelet/device-plugins
      resources: {}
  volumes:
    - name: kubelet-device-plugin-socket
      hostPath: { path: /var/lib/kubelet/device-plugins }
