apiVersion: v1
kind: Pod
metadata:
  name: intel-gpu-plugin-device-plugin
  namespace: kube-system
  labels:
    app: intel-gpu-plugin-device-plugin
spec:
  hostNetwork: true
  hostPID: true
  priorityClassName: system-node-critical
  tolerations:
    - operator: Exists
  containers:
    - name: intel-gpu-device-plugin
      image: intel/intel-gpu-plugin:latest
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      volumeMounts:
        - name: kubelet-device-plugin-socket
          mountPath: /var/lib/kubelet/device-plugins
      resources: {}
  volumes:
    - name: kubelet-device-plugin-socket
      hostPath: { path: /var/lib/kubelet/device-plugins }
